### ISSUE TITLE
Install fails on python3.4

### ISSUE THREAD

**Issue by alexcouper** [txels/ep#9]
```
$ pip install ep
Collecting ep
  Downloading ep-0.1.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/6b/ql76gbpn0wz53q4hl2bxg6lw0000gn/T/pip-build-g88l0eua/ep/setup.py", line 10, in <module>
        runtime_dependencies = Python.read_requirements('requirements/runtime.txt')
      File "/private/var/folders/6b/ql76gbpn0wz53q4hl2bxg6lw0000gn/T/pip-build-g88l0eua/ep/ep/python.py", line 73, in read_requirements
        with open(filename, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/runtime.txt'
```

**Comment by txels** [comment]
Fixed in 0.1.8 - in particular [here](https://github.com/txels/ep/commit/b40982f4789fd263f39b397d4e0d40a507be7aa1) - source distribution did not include requirements files, and apparently I had always been testing a 2.7 binary distribution for osx so far.
